class Sign
	attr_accessor :tokenId, :tokenString

	def initialize (tokenId, tokenString)
		self.tokenId     = tokenId;
		self.tokenString = tokenString;
	end
end

# Tous les signes, triés par nombre de caractères
SIGN_HASH = {
	ShiftRightUnsignedAssignment: 5 ,
	ShiftRightUnsigned: 42,
	StrictEqual: 43,
	StrictNotEqual: 44,
	ShiftLeftAssignment: 53,
	ShiftRightAssignment: 54,
	Equal: 19,
	LessOrEqual: 21,
	GreaterOrEqual: 23,
	NotEqual: 28,
	Increment: 37,
	Decrement: 38,
	Exponentiation: 39,
	ShiftLeft: 40,
	ShiftRight: 41,
	LogicalAnd: 45,
	LogicalXor: 46,
	LogicalOr: 47,
	PlusAssignment: 48,
	MinusAssignment: 49,
	MulAssignment: 50,
	DivAssignment: 51,
	ModAssignment: 52,
	AndAssignment: 56,
	XorAssignment: 57,
	OrAssignment: 58,
	NotAssignment: 59,
	Colon:  1,
	Comma:  2,
	Semicolon:  3,
	FullStop:  4,
	Plus:  5,
	Minus:  6,
	Asterisk:  7,
	Slash:  9,
	OpenParenthesis: 12,
	CloseParenthesis: 13,
	OpenBracket: 14,
	CloseBracket: 15,
	OpenBrace: 16,
	CloseBrace: 17,
	Assignment: 18,
	LessThan: 20,
	GreaterThan: 22,
	Ampersand: 24,
	Pipe: 25,
	Caret: 26,
	ExclamationMark: 27,
	QuestionMark: 29,
	Percent: 34,
	Tilde: 35
}

SIGN_HASH_DEBUG = {
	ShiftRightUnsignedAssignment: ">>>=",
	ShiftRightUnsigned: ">>>",
	StrictEqual: "===",
	StrictNotEqual: "!==",
	ShiftLeftAssignment: "<<=",
	ShiftRightAssignment: ">>=",
	Equal: "==" ,
	LessOrEqual: "<=" ,
	GreaterOrEqual: ">=" ,
	NotEqual: "!=" ,
	Increment: "++" ,
	Decrement: "--" ,
	Exponentiation: "**" ,
	ShiftLeft: "<<" ,
	ShiftRight: ">>" ,
	LogicalAnd: "&&" ,
	LogicalXor: "^^" ,
	LogicalOr: "||" ,
	PlusAssignment: "+=" ,
	MinusAssignment: "-=" ,
	MulAssignment: "*=" ,
	DivAssignment: "/=" ,
	ModAssignment: "%=" ,
	AndAssignment: "&=" ,
	XorAssignment: "^=" ,
	OrAssignment: "|=" ,
	NotAssignment: "~=" ,
	Colon: ":"  ,
	Comma: ","  ,
	Semicolon: ";"  ,
	FullStop: "."  ,
	Plus: "+"  ,
	Minus: "-"  ,
	Asterisk: "*"  ,
	Slash: "/"  ,
	OpenParenthesis: "("  ,
	CloseParenthesis: ")"  ,
	OpenBracket: "["  ,
	CloseBracket: "]"  ,
	OpenBrace: "{"  ,
	CloseBrace: "}"  ,
	Assignment: "="  ,
	LessThan: "<"  ,
	GreaterThan: ">"  ,
	Ampersand: "&"  ,
	Pipe: "|"  ,
	Caret: "^"  ,
	ExclamationMark: "!"  ,
	QuestionMark: "?"  ,
	Percent: "%"  ,
	Tilde: "~"
}

